// frontend-angular/src/app/components/complaint-card.component.ts
import { Component, Input, TemplateRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { Complaint } from '../shared/models';
import { STATUS_COLORS } from '../shared/constants';

@Component({
  selector: 'app-complaint-card',
  standalone: true,
  imports: [CommonModule, TranslateModule],
  template: `
    <div class="glass rounded-2xl p-4 shadow-card hover-lift fade-up fade-up-delay-1">
      <div class="flex items-start justify-between gap-3">
        <div>
          <h3 class="font-semibold text-slate-800">{{ complaint.title }}</h3>
          <p class="text-xs text-slate-500 mt-1">#{{ complaint.id }} - {{ ('categories.' + complaint.category) | translate }}</p>
        </div>
        <span class="text-xs px-2 py-1 rounded-full font-medium" [ngClass]="statusColors[complaint.status]">
          {{ ('status.' + complaint.status) | translate }}
        </span>
      </div>
      <p class="text-sm text-slate-600 mt-3 line-clamp-2">{{ complaint.description }}</p>
      <div class="mt-4 flex flex-wrap gap-3 text-xs text-slate-500">
        <span>📍 {{ complaint.location }}</span>
        <span>🗓️ {{ complaint.submissionDate | date : 'shortDate' }}</span>
      </div>
      <div *ngIf="actionTemplate" class="mt-4">
        <ng-container *ngTemplateOutlet="actionTemplate"></ng-container>
      </div>
    </div>
  `
})
export class ComplaintCardComponent {
  @Input({ required: true }) complaint!: Complaint;
  @Input() actionTemplate?: TemplateRef<unknown>;
  readonly statusColors = STATUS_COLORS;
}

// frontend/src/components/ComplaintCard.jsx
import { CalendarDays, MapPin } from 'lucide-react';
import { STATUS_COLORS } from '../utils/constants';

export default function ComplaintCard({ complaint, actionSlot }) {
  return (
    <div className="glass rounded-2xl p-4 shadow-card hover-lift fade-up fade-up-delay-1">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="font-semibold text-slate-800">{complaint.title}</h3>
          <p className="text-xs text-slate-500 mt-1">#{complaint.id} - {complaint.category.replace('_', ' ')}</p>
        </div>
        <span className={`text-xs px-2 py-1 rounded-full font-medium ${STATUS_COLORS[complaint.status]}`}>
          {complaint.status.replace('_', ' ')}
        </span>
      </div>
      <p className="text-sm text-slate-600 mt-3 line-clamp-2">{complaint.description}</p>
      <div className="mt-4 flex flex-wrap gap-3 text-xs text-slate-500">
        <span className="inline-flex items-center gap-1"><MapPin size={14} /> {complaint.location}</span>
        <span className="inline-flex items-center gap-1"><CalendarDays size={14} /> {new Date(complaint.submissionDate).toLocaleDateString()}</span>
      </div>
      {actionSlot ? <div className="mt-4">{actionSlot}</div> : null}
    </div>
  );
}
