// frontend-angular/src/app/components/rating-stars.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';

@Component({
  selector: 'app-rating-stars',
  standalone: true,
  imports: [CommonModule, TranslateModule],
  template: `
    <div class="flex items-center gap-2">
      <button *ngFor="let num of stars" type="button" (click)="change.emit(num)" [attr.aria-label]="('ratingStars.rate' | translate: { value: num })">
        <span class="text-2xl" [ngClass]="num <= value ? 'text-amber-400' : 'text-slate-300'">★</span>
      </button>
    </div>
  `
})
export class RatingStarsComponent {
  @Input() value = 0;
  @Output() change = new EventEmitter<number>();
  stars = [1, 2, 3, 4, 5];
}

// frontend/src/components/RatingStars.jsx
import { Star } from 'lucide-react';
import { useTranslation } from 'react-i18next';

export default function RatingStars({ value, onChange }) {
  const { t } = useTranslation();
  return (
    <div className="flex items-center gap-2">
      {[1, 2, 3, 4, 5].map((num) => (
        <button key={num} type="button" onClick={() => onChange(num)} aria-label={t('ratingStars.rate', { value: num, defaultValue: `Rate ${num} stars` })}>
          <Star
            size={26}
            className={num <= value ? 'fill-accent text-accent' : 'text-slate-300'}
          />
        </button>
      ))}
    </div>
  );
}
