// frontend-angular/src/app/components/sidebar.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { UserRole } from '../shared/models';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, TranslateModule],
  template: `
    <aside class="glass rounded-2xl p-4 shadow-card h-fit fade-up fade-up-delay-1">
      <p class="text-xs uppercase text-slate-500 mb-3">{{ 'sidebar.navigation' | translate }} 🧭</p>
      <nav class="space-y-2">
        <a
          *ngFor="let item of menuItems"
          [routerLink]="item.path"
          routerLinkActive="bg-primary text-white shadow-soft"
          [routerLinkActiveOptions]="{ exact: true }"
          class="flex items-center gap-3 rounded-xl px-3 py-2 transition hover-lift hover:bg-white/70 text-slate-600"
        >
          <span>{{ item.emoji }}</span>
          <span class="text-sm font-medium">{{ item.labelKey | translate }}</span>
        </a>
      </nav>
    </aside>
  `
})
export class SidebarComponent {
  @Input() role: UserRole | undefined;

  get menuItems() {
    const roleMenus: Record<string, Array<{ path: string; labelKey: string; emoji: string }>> = {
      CITIZEN: [
        { path: '/citizen', labelKey: 'sidebar.citizen.dashboard', emoji: '📊' },
        { path: '/submit', labelKey: 'sidebar.citizen.submit', emoji: '📨' },
        { path: '/my-complaints', labelKey: 'sidebar.citizen.myComplaints', emoji: '📋' }
      ],
      ADMIN: [
        { path: '/admin', labelKey: 'sidebar.admin.dashboard', emoji: '🛠️' },
        { path: '/analytics', labelKey: 'sidebar.admin.analytics', emoji: '📈' }
      ],
      OFFICER: [
        { path: '/officer', labelKey: 'sidebar.officer.panel', emoji: '🚓' },
        { path: '/officer-analytics', labelKey: 'sidebar.officer.analytics', emoji: '📊' }
      ]
    };
    return roleMenus[this.role || ''] || [];
  }
}

// frontend/src/components/Sidebar.jsx
import { Link, useLocation } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { LayoutDashboard, Send, ClipboardList, BarChart3, MessageSquareHeart } from 'lucide-react';

const roleMenus = {
  CITIZEN: [
    { path: '/citizen', labelKey: 'sidebar.citizen.dashboard', icon: LayoutDashboard },
    { path: '/submit', labelKey: 'sidebar.citizen.submit', icon: Send },
    { path: '/my-complaints', labelKey: 'sidebar.citizen.myComplaints', icon: ClipboardList }
  ],
  ADMIN: [
    { path: '/admin', labelKey: 'sidebar.admin.dashboard', icon: LayoutDashboard },
    { path: '/analytics', labelKey: 'sidebar.admin.analytics', icon: BarChart3 }
  ],
  OFFICER: [{ path: '/officer', labelKey: 'sidebar.officer.panel', icon: MessageSquareHeart }]
};

export default function Sidebar({ role }) {
  const { t } = useTranslation();
  const location = useLocation();
  const items = roleMenus[role] || [];

  return (
    <aside className="glass rounded-2xl p-4 shadow-card h-fit fade-up fade-up-delay-1">
      <p className="text-xs uppercase text-slate-500 mb-3">{t('sidebar.navigation')} 🧭</p>
      <nav className="space-y-2">
        {items.map(({ path, labelKey, icon: Icon }) => {
          const active = location.pathname === path;
          return (
            <Link
              key={path}
              to={path}
              className={`flex items-center gap-3 rounded-xl px-3 py-2 transition hover-lift ${
                active ? 'bg-primary text-white shadow-soft' : 'hover:bg-white/70 text-slate-600'
              }`}
            >
              <Icon size={18} />
              <span className="text-sm font-medium">{t(labelKey)}</span>
            </Link>
          );
        })}
      </nav>
    </aside>
  );
}
